### ISSUE TITLE
UI issues in users view

### ISSUE THREAD

**Issue by vohmar** [internetee/auction_center#462]
https://prnt.sc/q8ueun

Thanks to Artur who pointed out few issues in users view

* the second error message begins with lower cap letter (translation?)
  * in addition to that there is a grammar issue with the second error message. Correct message would be: "Kasutajatingimustega peab nõustuma"
* the spacing between name of the field and input field of pssword and repeat password blocks is inconsistent with rest of the form

**Comment by yulgolem** [comment]
![image](https://user-images.githubusercontent.com/7688888/71250390-5be80480-2341-11ea-926b-0e41260a3771.png)

**Comment by vohmar** [comment]
problems are still there in english view:

* kasutaja tingimused is missing english translation
* once the error is returned the font and spacing of the first password field are changed

![image](https://user-images.githubusercontent.com/7734747/71519365-ed1a2680-28bf-11ea-879d-6ffa45fd28ec.png)

**Comment by vohmar** [comment]
the password issue is there in estonian as well:

![image](https://user-images.githubusercontent.com/7734747/71519541-a0831b00-28c0-11ea-8b98-3ef4039e4ac4.png)

**Comment by yulgolem** [comment]
Fixed in EN locale:
![image](https://user-images.githubusercontent.com/7688888/71520658-08e0f500-28df-11ea-84ae-e019c3a72cfa.png)
Fixen in ET locale:
![image](https://user-images.githubusercontent.com/7688888/71520699-2a41e100-28df-11ea-8d66-40623d680d81.png)

**Comment by vohmar** [comment]
in english I still see salasõna not translated:

![image](https://user-images.githubusercontent.com/7734747/71523687-b8639a80-28d2-11ea-9c5d-444eecaa58a8.png)

**Comment by vohmar** [comment]
steps to reproduce:
* Go to auction protal and select english language
* Click on sign in link top right
* Click "Create an account"
* Fill the form
  * email: asdfa@asdfa.esf
  * mobile phone: +3721234
  * given names: asdfa
  * surename: asdfa
*  Click "sign up"
* 2 errers are returned - pic in the previous comment
